function p = toastCatchErrors
%toastCatchErrors     - Catch errors generated by the toast libraries.
%
% Synopsis: toastCatchErrors()
%
% Overrides the default error handling method of the toast libraries.
% Subsequently, toast library errors will no longer cause the matlab
% process to terminate, but instead echo an error message and return to
% the Matlab prompt.
  
