include $(TOASTDIR)/Makefile.incl

LIBNAME = libdgfe
LIB = $(LIBNAME)$(LIB_SUFFIX)

VPATH = $(TSRC)/libdgfe

all:: $(LIB)

SRCS = 	nonconformingMesh.cc dgfwdsolver.cc dgSource.cc

OBJS = ${SRCS:.cc=.o}
HDRS = nonconformingMesh.h dgfwdsolver.h dgSource.h

%.o : %.cc $(HDRS)
	$(CXX) -fPIC $(STOASTINC) -c $<

$(LIBNAME)$(SHLIB_SUFFIX): $(OBJS)
	@$(RM) $@
	$(SHLIB_LD) -o $@ $^
	
clean:: 
	$(RM) *.o

distclean:: clean
	$(RM) Makefile
	$(RM) $(LIB)
