#ifndef _SPARSPAK_H
#define _SPARSPAK_H

/************ namessparspack.h einbinden, falls noch nicht geschehen *********/
#include "namessparspak.h"

#include "long_integer.h"

/* Common Block Declarations */
extern struct 
{
    double ops;
}
spkops;


void      bshufl(integer *, integer *, integer *, integer *, integer *, 
		 integer *, integer *, integer *, integer *),
          copysi(integer *, integer *, integer *),
          degree(integer *, integer *, integer *, integer *, integer *, 
		 integer *, integer *),
          elslv(integer *, integer *, doubleprecision *, doubleprecision *, 
		doubleprecision *),
          esfct(integer *, integer *, doubleprecision *, doubleprecision *, integer *),
          euslv(integer *, integer *, doubleprecision *, doubleprecision *, 
		doubleprecision *),
          fnbenv(integer *, integer *, integer *, integer *, integer *, 
		 integer *, integer *, integer *, integer *, integer *, 
		 integer *),
          fndsep(integer *, integer *, integer *, integer *, integer *, 
		 integer *, integer *, integer *),
          fnenv(integer *, integer *, integer *, integer *, integer *, 
		integer *, integer *, integer *),
          fnlvls(integer *, integer *, integer *, integer *, integer *, 
		 integer *, integer *),
          fnofnz(integer *, integer *, integer *, integer *, integer *, 
		 integer *, integer *, integer *, integer *),
          fnroot(integer *, integer *, integer *, integer *, integer *, 
		 integer *, integer *),
          fnspan(integer *, integer *, integer *, integer *, integer *, 
		 integer *, integer *, integer *, integer *),
          fntadj(integer *, integer *, integer *, integer *, integer *, 
		 integer *, integer *, integer *),
          fntenv(integer *, integer *, integer *, integer *, integer *, 
		 integer *, integer *, integer *),
          fn1wd(integer *, integer *, integer *, integer *, integer *, 
		integer *, integer *, integer *, integer *),
          gennd(integer *, integer *, integer *, integer *, integer *, 
		integer *, integer *),
          genqmd(integer *, integer *, integer *, integer *, integer *, 
		 integer *, integer *, integer *, integer *, integer *, 
		 integer *, integer *),
          genrcm(integer *, integer *, integer *, integer *, integer *, 
		 integer *),
          genrqt(integer *, integer *, integer *, integer *, integer *, 
		 integer *, integer *, integer *, integer *),
          gen1wd(integer *, integer *, integer *, integer *, integer *, 
		 integer *, integer *, integer *, integer *),
          gsfct(integer *, integer *, doubleprecision *, integer *, integer *, 
		doubleprecision *, integer *, integer *, doubleprecision *, integer *),
          gsslv(integer *, integer *, doubleprecision *, integer *, integer *, 
		doubleprecision *, doubleprecision *),
          guslv(integer *, integer *, doubleprecision *, integer *, integer *, 
		doubleprecision *, doubleprecision *),
          glslv(integer *, integer *, doubleprecision *, integer *, integer *, 
		doubleprecision *, doubleprecision *),
          qmdmrg(integer *, integer *, integer *, integer *, integer *, 
		 integer *, integer *, integer *, integer *, integer *,
		 integer *),
          qmdqt(integer *, integer *, integer *, integer *, integer *, 
		integer *, integer *),
          qmdrch(integer *, integer *, integer *, integer *, integer *, 
		 integer *, integer *, integer *, integer *),
          qmdupd(integer *, integer *, integer *, integer *, integer *, 
		 integer *, integer *, integer *, integer *, integer *),
          rcm(integer *, integer *, integer *, integer *, integer *, 
	      integer *, integer *),
          reach(integer *, integer *, integer *, integer *, integer *, 
		integer *, integer *, integer *, integer *),
          rootls(integer *, integer *, integer *, integer *, integer *, 
		 integer *, integer *),
          rqtree(integer *, integer *, integer *, integer *, integer *, 
		 integer *, integer *, integer *, integer *),
          smbfct(integer *, integer *, integer *, integer *, integer *, 
		 integer *, integer *, integer *, integer *, integer *,
		 integer *, integer *, integer *, integer *),
          sorts1(integer *, integer *),
          subrcm(integer *, integer *, integer *, integer *, integer *, 
		 integer *, integer *),
          tsfct(integer *, integer *, integer *, doubleprecision *, integer *, 
		doubleprecision *, integer *, doubleprecision *, integer *, 
		doubleprecision *, integer *, integer *),
          tsslv(integer *, integer *, doubleprecision *, integer *, doubleprecision *, 
		integer *, doubleprecision *, integer *, doubleprecision *, 
		doubleprecision *),
          invrse(integer *, integer *, integer *),
          revrse(integer *, integer *),
          permrv(integer *, doubleprecision *, integer *),
          chlsetup(integer *, integer *, doubleprecision *, integer *, integer *,
		   doubleprecision *, integer *, integer *, doubleprecision *, 
		   integer *, integer *, integer *, integer *),
          suslv(integer *,integer *,doubleprecision *,integer *,integer *,
		doubleprecision *,integer *,doubleprecision *,integer *, doubleprecision *),
          slslv(integer *,integer *,doubleprecision *,integer *,integer *, 
		doubleprecision *,integer *,doubleprecision *,integer *,doubleprecision *),
          fuslv(integer *,integer *,doubleprecision *,integer *,integer *,
		doubleprecision *,integer *,doubleprecision *),
          flslv(integer *,integer *,doubleprecision *,integer *,integer *,
		doubleprecision *,integer *,doubleprecision *);

#endif /* _SPARSPAK_H */
