include $(TOASTDIR)/Makefile.incl
SHELL = /bin/csh
VPATH = $(TSRC)/matlab2

TGTSRC = toast.cc
TGTOBJ = ${TGTSRC:.cc=.$(MEXEXT)}

AUXSRC = matlabtoast.cc toastmex.cc util.cc mtMesh.cc mtBasis.cc mtField.cc mtGradient.cc mtJacobian.cc mtRegul.cc

ifeq ($(BUILD_FDOT),1)
  AUXSRC +=  matlabfdot.cc
endif

AUXOBJ = ${AUXSRC:.cc=.o}

all:: $(TGTOBJ)

%.o : %.cc
	$(MEX) -c $<

%.$(MEXEXT) : %.cc $(AUXOBJ)
	$(MEX) $^

clean::
	rm -f *.$(MEXEXT)
	rm -f *.o
