include $(TOASTDIR)/Makefile.incl

LIBNAME = libbemdiff

LIB = $(TLIB)/$(LIBNAME)$(LIB_SUFFIX)

VPATH = $(TSRC)/libbemdiff

all:: $(LIB)

SRCS =  bemdiff.cc 

OBJS = ${SRCS:.cc=.o}
HDRS = ${SRCS:.cc=.h}

#%.cc: %.h
#	touch $@

%.o : %.cc $(HDRS)
	$(CXX) $(FLAGS) $(SHLIB_CFLAGS) -c $<

$(LIB): $(OBJS)
	@$(RM) $(LIB)
	$(MAKE_LIB)
	$(RANLIB) $(LIB)

clean:: 
	$(RM) *.o *~

distclean:: clean
	$(RM) Makefile
	$(RM) $(LIB)
